spring:
  data:
    mongodb:
      uri: mongodb+srv://mertkocmrt:FRMFTH94IOFacP8U@cluster0.ah9x1.mongodb.net/portal?retryWrites=true&w=majority
logging:
  level:
    org:
      springframework:
        data.mongodb: INFO
        boot.autoconfigure.mongo: INFO
    com.mongodb.client: INFO